baseurl = "/"
title = "Eldridge Alexander"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Eldridge Alexander"
    info = "Information Security"
    description = "Eldridge's personal website"
    keywords = "blog,developer,personal,engineer,security,infosec"
    avatarurl = "img/eldridge_alexander.jpg"

    favicon_32 = "favicon.ico"
    favicon_16 = "/img/favicon-16x16.png"

#    footercontent = "© Eldridge Alexander"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/eldridgea/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/magiceldridge/"
[[params.social]]
    name = "Mastodon"
    icon = "fab fa-mastodon fa-2x"
    weight = 4
    url = "https://infosec.exchange/@eldridge"
[[params.social]]
    name = "YouTube"
    icon = "fab fa-youtube fa-2x"
    weight = 5
    url = "https://www.youtube.com/channel/UCcGHxtDSfSmH9SuR-nWb6WA"

# Menu links
[[menu.main]]
    name = "Home"
    weight = 100
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = 300
    url  = "https://blog.eldrid.ge"
[[menu.main]]
    name = "Portfolio"
    weight = 400
    url  = "/portfolio"